$(document).ready(function(){
    $(".togMenu").click(function(){
        $(".catPanel").toggle();
    });
    $(".togMenuC").click(function(){
        $(".colPanel").toggle();
    });
    $(".togMenuM").click(function(){
        $(".matPanel").toggle();
    });
});
